# Generated by Django 4.2.4 on 2023-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0002_contacts_active_contacts_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
    ]
