# Generated by Django 4.2.4 on 2023-09-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0004_servicesslide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesSlide',
            new_name='Slide',
        ),
    ]
