# Generated by Django 4.2.4 on 2023-09-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0005_rename_servicesslide_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog_image/')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('date_created', models.DateField()),
                ('active_in_footer', models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], null=True)),
                ('slug_of_service_slide', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('subimage', models.ImageField(blank=True, null=True, upload_to='activity_image/')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ballinat.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ballinat.subtitle')),
            ],
        ),
    ]
