# Generated by Django 4.2.4 on 2023-09-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0006_blog_subtitle_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug_of_service_slide',
            new_name='slug_blog',
        ),
    ]
