# Generated by Django 4.2.4 on 2023-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0012_alter_slide_title_part1_alter_slide_title_part2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
    ]
