# Generated by Django 4.2.4 on 2023-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0013_slide_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknikat',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
    ]
