# Generated by Django 4.2.4 on 2023-09-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0014_teknikat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ballinat.aboutus'),
        ),
    ]
