# Generated by Django 4.2.4 on 2023-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0015_paragraphs_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterslides',
            name='prapavija',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
