# Generated by Django 4.2.4 on 2023-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballinat', '0017_alter_afterslides_prapavija'),
    ]

    operations = [
        migrations.AddField(
            model_name='punim',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
